python boba_quest_immersive.py \
  --case_name hybrid_rope_game \
  --n_dup 0 \
  --interactive_window_mode hidden \
  --immersive_static_scene_backend native_gl \
  --immersive_static_scene_overlap on \
  --immersive_present_pipeline off \
  --immersive_static_scene_reuse adaptive \
  --immersive_gaussian_render stereo_batched \
  --immersive_native_gl_texture_mode stable_mipmap \
  --immersive_native_gl_anisotropy 8 \
  --immersive_native_gl_mipmap_lod_bias 0.50 \
  --immersive_native_gl_msaa_samples 4 \
  --immersive_native_gl_depth_format depth32f \
  --immersive_eye_resolution 1344 \
  --immersive_controller_translation_scale 0.25 \
  --immersive_viewer_upload_mode pbo \
  --immersive_viewer_upload_thread auto

python boba_quest_immersive.py \
  --case_name sloth \
  --n_dup 0 \
  --interactive_window_mode hidden \
  --immersive_static_scene_backend native_gl \
  --immersive_static_scene_overlap on \
  --immersive_present_pipeline off \
  --immersive_static_scene_reuse adaptive \
  --immersive_gaussian_render stereo_batched \
  --immersive_native_gl_texture_mode stable_mipmap \
  --immersive_native_gl_anisotropy 8 \
  --immersive_native_gl_mipmap_lod_bias 0.50 \
  --immersive_native_gl_msaa_samples 4 \
  --immersive_native_gl_depth_format depth32f \
  --immersive_eye_resolution 1344 \
  --immersive_controller_translation_scale 0.5 \
  --immersive_viewer_upload_mode pbo \
  --immersive_viewer_upload_thread auto
